terminate called after throwing an instance of 'boost::wrapexcept<std::overflow_error>'
  what():  Error in function boost::math::erfc_inv<long double>(long double, long double): Overflow Error
==1839561==  If you believe this happened as a result of a stack
==1839561==  overflow in your program's main thread (unlikely but
==1839561==  possible), you can try to increase the size of the
==1839561==  main thread stack using the --main-stacksize= flag.
==1839561==  The main thread stack size used in this run was 8388608.
Segmentation fault
